// Generated by scripts/build-resonance-engine.js. Edit the source utilities, then regenerate.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_RESONANCE_CONFIG = exports.WINDOW_HOUR_OPTIONS = void 0;
exports.coinKey = coinKey;
exports.readResonanceConfig = readResonanceConfig;
exports.writeResonanceWindowHours = writeResonanceWindowHours;
exports.mergeRowsByWhale = mergeRowsByWhale;
exports.selectResonanceSignals = selectResonanceSignals;
exports.scanResonanceSignals = scanResonanceSignals;
const WAN = 10000, YI = 100000000, MAINTENANCE_MARGIN_RATE = 0.004;
function formatWanNumber(abs) {
    const wan = abs / WAN;
    if (wan >= 100)
        return wan.toFixed(0);
    if (wan >= 10)
        return trimTrailingZeros(wan.toFixed(1));
    return trimTrailingZeros(wan.toFixed(2));
}
function formatYiNumber(abs) {
    const yi = abs / YI;
    if (yi >= 100)
        return yi.toFixed(0);
    if (yi >= 10)
        return trimTrailingZeros(yi.toFixed(1));
    return trimTrailingZeros(yi.toFixed(2));
}
function formatUsd(value) {
    if (value == null || Number.isNaN(Number(value)))
        return '--';
    const n = Number(value);
    const sign = n < 0 ? '-' : '';
    const abs = Math.abs(n);
    // U+2060 word joiner：避免「亿/万」与数字被拆到两行
    if (abs >= YI) {
        return `${sign}$${formatYiNumber(abs)}\u2060亿`;
    }
    if (abs >= WAN) {
        return `${sign}$${formatWanNumber(abs)}\u2060万`;
    }
    return `${sign}$${abs.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}
function trimTrailingZeros(value) {
    if (!value.includes('.'))
        return value;
    return value.replace(/(\.\d*?[1-9])0+$/, '$1').replace(/\.0+$/, '');
}
function estimateLiquidationPx(side, entryPx, leverage) {
    if (!entryPx || !leverage || leverage < 1)
        return null;
    const im = 1 / leverage;
    if (side === 'long')
        return entryPx * (1 - im + MAINTENANCE_MARGIN_RATE);
    return entryPx * (1 + im - MAINTENANCE_MARGIN_RATE);
}
function alertEventTime(item) {
    const times = (item.items || [])
        .map((entry) => Number(entry.time) || 0)
        .filter((value) => value > 0);
    if (times.length)
        return Math.max(...times);
    return Number(item.at) || 0;
}
function tradeFillSide(trade) {
    if (trade.source === 'onchain') {
        return trade.side === 'buy' || trade.side === 'in' ? 'long' : 'short';
    }
    if (Math.abs(Number(trade.closedPnl) || 0) > 1) {
        return trade.side === 'sell' ? 'long' : 'short';
    }
    return trade.side === 'buy' ? 'long' : 'short';
}
function inferSide(alert, item) {
    if (item?.side === 'long' || item?.side === 'short')
        return item.side;
    const text = `${item?.title || ''} ${alert.headline || ''}`;
    if (/开多|平多|做多/.test(text))
        return 'long';
    if (/开空|平空|做空/.test(text))
        return 'short';
    if (/买入|^买/.test(text))
        return 'long';
    if (/卖出|^卖/.test(text))
        return 'short';
    return null;
}
function normalizeCoinId(value) {
    return String(value || '')
        .trim()
        .toUpperCase()
        .replace(/[^A-Z0-9]/g, '');
}
function coinMatchesWatch(coin, watched = readWatchedCoins()) {
    const key = normalizeCoinId(String(coin || ''));
    if (!key || !watched.length)
        return false;
    return watched.some((item) => {
        const watch = normalizeCoinId(item);
        if (!watch)
            return false;
        if (key === watch)
            return true;
        if (key === `U${watch}` || key === `K${watch}`)
            return true;
        if (key.endsWith(watch) && key.length <= watch.length + 4)
            return true;
        const stripped = key.replace(/^U/, '').replace(/^K/, '');
        return stripped === watch;
    });
}
function readWatchedCoins() { return []; }
const STORAGE_KEY = 'whale-tracker-resonance-window-h';
exports.WINDOW_HOUR_OPTIONS = [
    { label: '2小时', value: 2 },
    { label: '4小时', value: 4 },
    { label: '6小时', value: 6 },
    { label: '12小时', value: 12 },
    { label: '24小时', value: 24 },
];
const ALLOWED_WINDOW_HOURS = new Set(exports.WINDOW_HOUR_OPTIONS.map((item) => item.value));
exports.DEFAULT_RESONANCE_CONFIG = {
    windowHours: 6,
    minWhales: 3,
    minNotionalUsd: 50000,
    minWinRate: 70,
    mergeMinutes: 5,
    accumulationWindowHours: 6,
    accumulationMinOpens: 3,
    accumulationMinTotalUsd: 500000,
};
function coinKey(coin) {
    return String(coin || '').toUpperCase().replace(/^K/, '');
}
function coinLabel(trade) {
    const raw = trade.assetLabel || trade.asset || '';
    return coinKey(raw) || raw || '--';
}
function tradePrice(trade) {
    if (Number(trade.price) > 0)
        return Number(trade.price);
    if (Number(trade.amount) > 0 && Number(trade.amountUsd) > 0) {
        return Number(trade.amountUsd) / Number(trade.amount);
    }
    return 0;
}
function normalizeWindowHours(value) {
    const n = Number(value);
    if (ALLOWED_WINDOW_HOURS.has(n))
        return n;
    if (n === 48 || n === 72)
        return 24;
    return exports.DEFAULT_RESONANCE_CONFIG.windowHours;
}
function shortWhaleLabel(name, address) {
    const addr = String(address || '').toLowerCase();
    if (addr.startsWith('0x') && addr.length > 10)
        return `0x…${addr.slice(-4)}`;
    return name || '--';
}
function readResonanceConfig() {
    try {
        const saved = localStorage.getItem(STORAGE_KEY);
        const windowHours = normalizeWindowHours(saved);
        if (saved != null && Number(saved) !== windowHours) {
            writeResonanceWindowHours(windowHours);
        }
        return {
            ...exports.DEFAULT_RESONANCE_CONFIG,
            windowHours,
        };
    }
    catch {
        return { ...exports.DEFAULT_RESONANCE_CONFIG };
    }
}
function writeResonanceWindowHours(windowHours) {
    localStorage.setItem(STORAGE_KEY, String(normalizeWindowHours(windowHours)));
}
function openMerger(mergeMs) {
    const merged = [];
    const latest = new Map();
    function add(row) {
        const key = `${row.whaleId}|${row.coin}|${row.side}`;
        const prev = latest.get(key);
        // Fixed span from the first execution, not an indefinitely sliding chain.
        if (prev && row.time - (prev.firstTime ?? prev.time) <= mergeMs) {
            const total = prev.notionalUsd + row.notionalUsd;
            prev.price = total > 0 ? (prev.price * prev.notionalUsd + row.price * row.notionalUsd) / total : prev.price;
            prev.notionalUsd = total;
            if (row.action === "open")
                prev.action = "open";
            prev.time = row.time;
        }
        else {
            const next = { ...row, firstTime: row.time };
            merged.push(next);
            latest.set(key, next);
        }
    }
    return { add, merged };
}
function mergeOpens(rows, mergeMs) {
    const merger = openMerger(mergeMs);
    for (const row of [...rows].sort((a, b) => a.time - b.time))
        merger.add(row);
    return merger.merged;
}
function buildClusterBannerText(signal, windowHours) {
    const sideText = signal.side === 'long' ? '开多' : '开空';
    const bias = signal.side === 'long' ? '短线偏多' : '短线偏空';
    return `【${signal.coin}】${windowHours}h内 ${signal.whaleCount}巨鲸同向${sideText}（总${formatUsd(signal.totalUsd)}）→ ${bias}`;
}
function buildAccumulationBannerText(signal, windowHours) {
    const sideText = signal.side === 'long' ? '做多' : '做空';
    const bias = signal.side === 'long' ? '主力吸筹' : '主力派发';
    const label = shortWhaleLabel(signal.whaleName || signal.rows[0]?.whaleName || '', signal.rows[0]?.address || '');
    return `【${signal.coin}】${windowHours}h内 ${label} 持续${sideText}开/加仓（${signal.tradeCount}笔·总${formatUsd(signal.totalUsd)}）→ ${bias}`;
}
function isOpenAlertKind(kind) {
    return kind === 'open';
}
function alertSignalItems(alert) {
    if (alert.items?.length) {
        return alert.items.filter((item) => isOpenAlertKind(item.kind) || item.kind === 'increase');
    }
    if (!isOpenAlertKind(alert.kind) && alert.kind !== 'increase')
        return [];
    return [
        {
            kind: alert.kind,
            title: alert.headline || '',
            detail: '',
            coin: '',
            side: undefined,
            usd: 0,
            price: 0,
            time: alert.at,
        },
    ];
}
/** 成交方向只有在成交前仓位明确为空时，才能作为「新开仓」计入共振。
 * Hyperliquid 的 dir 会把加仓也标成 Open Long/Short，因此不能单独依赖 dir；
 * 缺 startPosition 的旧记录不猜方向/开平，避免把平仓成交当作反向新开仓。
 */
function classifyFillAction(trade) {
    if (!trade || trade.source === 'onchain' || trade.startPosition == null)
        return null;
    const startPosition = Number(trade.startPosition);
    if (!Number.isFinite(startPosition) || Math.abs(Number(trade.closedPnl) || 0) > 1)
        return null;
    if (Math.abs(startPosition) < 1e-8)
        return 'open';
    const side = String(trade.side || '').toLowerCase();
    const addsToLong = startPosition > 0 && (side === 'buy' || side === 'b' || side === 'in');
    const addsToShort = startPosition < 0 && (side === 'sell' || side === 'a' || side === 'out');
    return addsToLong || addsToShort ? 'increase' : null;
}
function* rowsFromAlerts(alerts, whaleMap, since) {
    for (const alert of alerts) {
        const whale = whaleMap.get(alert.whaleId);
        if (!whale)
            continue;
        for (const item of alertSignalItems(alert)) {
            // 未能关联真实成交时间的快照只用于异动提示，不参与时间窗共振判断。
            if (item.evidenceSource === 'snapshot' && item.timeSource === 'observed')
                continue;
            const time = Number(item.time) || alertEventTime(alert);
            if (!time || time < since)
                continue;
            const notionalUsd = Number(item.usd) || 0;
            if (!(notionalUsd > 0))
                continue;
            const coin = coinKey(item.coin || '');
            if (!coin)
                continue;
            const side = item.side || inferSide(alert, item);
            if (!side)
                continue;
            yield buildOpenRow(whale, {
                sourceId: item.sourceId || `${alert.id}:${item.coin}:${item.side}:${item.kind}:${time}`,
                whaleId: alert.whaleId,
                whaleName: alert.whaleName || whale.name,
                address: alert.address || whale.address,
                coin,
                side,
                action: item.kind === 'increase' ? 'increase' : 'open',
                price: Number(item.price) || 0,
                notionalUsd,
                time,
                winRate: Number(whale.winRate) || 0,
            });
        }
    }
}
function dedupeRows(rows) {
    const map = new Map();
    for (const row of rows) {
        const key = row.sourceId || `${row.whaleId}|${row.coin}|${row.side}|${row.action}|${row.time}|${row.notionalUsd}`;
        const prev = map.get(key);
        if (!prev)
            map.set(key, row);
    }
    return [...map.values()];
}
function matchWhalePosition(whale, coin, side) {
    const key = coinKey(coin);
    return (whale.positions || []).find((pos) => coinKey(pos.coinLabel || pos.coin) === key && pos.side === side);
}
function resolveOpenMetrics(whale, coin, side, price) {
    const pos = matchWhalePosition(whale, coin, side);
    const leverage = pos?.leverage && pos.leverage > 0 ? Number(pos.leverage) : null;
    let liquidationPx = null;
    if (pos?.liquidationPx) {
        const liq = Number(pos.liquidationPx);
        liquidationPx = Number.isFinite(liq) && liq > 0 ? liq : null;
    }
    if (!liquidationPx && leverage && price > 0) {
        liquidationPx = estimateLiquidationPx(side, price, leverage);
    }
    return { leverage, liquidationPx };
}
function buildOpenRow(whale, base) {
    const metrics = resolveOpenMetrics(whale, base.coin, base.side, base.price);
    return { ...base, ...metrics };
}
/** 明细表：同一巨鲸、同币种同方向的多笔开仓合并为一行，金额与价格仅使用信号期间的成交 */
function mergeRowsByWhale(rows, whaleMap) {
    const groups = new Map();
    for (const row of rows) {
        const key = `${row.whaleId}|${row.coin}|${row.side}`;
        const list = groups.get(key) || [];
        list.push(row);
        groups.set(key, list);
    }
    return [...groups.values()]
        .map((group) => {
        const sorted = [...group].sort((a, b) => b.time - a.time);
        const latest = sorted[0];
        const openCount = group.length;
        const signalNotional = group.reduce((sum, item) => sum + item.notionalUsd, 0);
        const signalPrice = signalNotional > 0
            ? group.reduce((sum, item) => sum + item.price * item.notionalUsd, 0) / signalNotional
            : latest.price;
        const whale = whaleMap?.get(latest.whaleId);
        const price = signalPrice;
        const notionalUsd = signalNotional;
        const metrics = whale
            ? resolveOpenMetrics(whale, latest.coin, latest.side, price)
            : { leverage: latest.leverage, liquidationPx: latest.liquidationPx };
        return {
            ...latest,
            price,
            notionalUsd,
            time: latest.time,
            winRate: Number(whale?.winRate) || latest.winRate,
            openCount,
            ...metrics,
        };
    })
        .sort((a, b) => b.notionalUsd - a.notionalUsd);
}
function collectOpenRows(input) {
    const whaleMap = new Map(input.whales.map((item) => [item.id, item]));
    const watched = input.watchedCoins?.length ? input.watchedCoins : readWatchedCoins();
    function* candidates() {
        for (const trade of input.activity) {
            const action = classifyFillAction(trade);
            if (!trade.whaleId || !action)
                continue;
            if (trade.time < input.since)
                continue;
            const whale = whaleMap.get(trade.whaleId);
            if (!whale)
                continue;
            const notionalUsd = Number(trade.amountUsd) || 0;
            if (!(notionalUsd > 0))
                continue;
            yield buildOpenRow(whale, {
                sourceId: `fill:${String(trade.id).startsWith(`${trade.whaleId}:`) ? trade.id : `${trade.whaleId}:${trade.id}`}`,
                whaleId: trade.whaleId,
                whaleName: trade.whaleName || whale.name,
                address: whale.address,
                coin: coinLabel(trade),
                action,
                side: tradeFillSide(trade),
                price: tradePrice(trade),
                notionalUsd,
                time: trade.time,
                winRate: Number(whale.winRate) || 0,
            });
        }
        yield* rowsFromAlerts(input.alerts || [], whaleMap, input.since);
    }
    function* eligible() {
        for (const row of candidates()) {
            if (coinMatchesWatch(row.coin, watched) && row.winRate >= input.config.minWinRate)
                yield row;
        }
    }
    return input.sortedUniqueAlerts ? eligible() : dedupeRows(eligible());
}
function scanClusterSignals(rows, config) {
    const groups = new Map();
    for (const row of rows) {
        const key = `${row.coin}|${row.side}`;
        const list = groups.get(key) || [];
        list.push(row);
        groups.set(key, list);
    }
    const signals = [];
    for (const [groupKey, groupRows] of groups) {
        const whaleIds = new Set(groupRows.map((item) => item.whaleId));
        if (whaleIds.size < config.minWhales)
            continue;
        const coin = groupRows[0].coin;
        const side = groupRows[0].side;
        const totalUsd = groupRows.reduce((sum, item) => sum + item.notionalUsd, 0);
        const signal = {
            id: `cluster|${groupKey}`,
            kind: 'cluster',
            coin,
            side,
            whaleCount: whaleIds.size,
            tradeCount: groupRows.length,
            totalUsd,
            rows: [...groupRows].sort((a, b) => b.time - a.time),
            bannerText: '',
            biasLabel: side === 'long' ? '短线偏多' : '短线偏空',
        };
        signal.bannerText = buildClusterBannerText(signal, config.windowHours);
        signals.push(signal);
    }
    return signals;
}
function scanAccumulationSignals(rows, config, now) {
    const since = now - config.accumulationWindowHours * 3600000;
    const recent = rows.filter((row) => row.time >= since);
    const groups = new Map();
    for (const row of recent) {
        const key = `${row.whaleId}|${row.coin}|${row.side}`;
        const list = groups.get(key) || [];
        list.push(row);
        groups.set(key, list);
    }
    const signals = [];
    for (const [groupKey, groupRows] of groups) {
        if (groupRows.length < config.accumulationMinOpens)
            continue;
        const totalUsd = groupRows.reduce((sum, item) => sum + item.notionalUsd, 0);
        if (totalUsd < config.accumulationMinTotalUsd)
            continue;
        const sortedRows = [...groupRows].sort((a, b) => b.time - a.time);
        const first = sortedRows[0];
        const signal = {
            id: `accumulation|${groupKey}`,
            kind: 'accumulation',
            coin: first.coin,
            side: first.side,
            whaleCount: 1,
            tradeCount: groupRows.length,
            totalUsd,
            rows: sortedRows,
            bannerText: '',
            biasLabel: first.side === 'long' ? '主力吸筹' : '主力派发',
            whaleId: first.whaleId,
            whaleName: first.whaleName,
        };
        signal.bannerText = buildAccumulationBannerText(signal, config.accumulationWindowHours);
        signals.push(signal);
    }
    return signals;
}
function sortSignals(a, b) {
    if (a.kind !== b.kind) {
        return a.kind === 'accumulation' ? -1 : 1;
    }
    if (b.totalUsd !== a.totalUsd)
        return b.totalUsd - a.totalUsd;
    if (b.whaleCount !== a.whaleCount)
        return b.whaleCount - a.whaleCount;
    return b.tradeCount - a.tradeCount;
}
function primaryBySignalSide(signals) {
    const totals = new Map();
    for (const signal of signals) {
        const total = totals.get(signal.side) || { signals: 0, rows: 0, whales: 0, usd: 0 };
        total.signals += 1;
        total.rows += signal.tradeCount;
        total.whales += signal.whaleCount;
        total.usd += signal.totalUsd;
        totals.set(signal.side, total);
    }
    const long = totals.get('long') || { signals: 0, rows: 0, whales: 0, usd: 0 };
    const short = totals.get('short') || { signals: 0, rows: 0, whales: 0, usd: 0 };
    const winningSide = short.signals !== long.signals
        ? (short.signals > long.signals ? 'short' : 'long')
        : short.rows !== long.rows
            ? (short.rows > long.rows ? 'short' : 'long')
            : short.whales !== long.whales
                ? (short.whales > long.whales ? 'short' : 'long')
                : short.usd > long.usd ? 'short' : 'long';
    return [...signals].filter((signal) => signal.side === winningSide).sort(sortSignals)[0] || signals[0] || null;
}
// Filtering completed per-coin signals preserves the scanner's side selection
// without re-reading executions when a user changes their watched coins.
function selectResonanceSignals(signals, watched) {
    const selected = signals.filter(signal => coinMatchesWatch(signal.coin, watched));
    return {
        hit: selected.length > 0,
        primary: primaryBySignalSide(selected),
        signals: selected,
        emptyText: watched.length ? `暂无 ${watched.join(' / ')} 共振或持续加仓信号` : '暂无巨鲸共振或持续加仓信号',
    };
}
function scanResonanceSignals(input) {
    const config = input.config || readResonanceConfig();
    const now = input.now ?? Date.now();
    const watched = input.watchedCoins?.length ? input.watchedCoins : readWatchedCoins();
    const since = now - config.windowHours * 3600000;
    const mergeMs = config.mergeMinutes * 60000;
    const lookbackHours = Math.max(config.windowHours, config.accumulationWindowHours);
    const collectionSince = now - lookbackHours * 3600000;
    const dedupedRows = collectOpenRows({
        activity: input.activity,
        alerts: input.alerts || [],
        whales: input.whales,
        since: collectionSince,
        config,
        watchedCoins: watched,
        sortedUniqueAlerts: input.sortedUniqueAlerts && input.activity.length === 0,
    });
    let clusterMerged, accumulationMerged;
    const accumulationSince = now - config.accumulationWindowHours * 3600000;
    if (input.sortedUniqueAlerts && input.activity.length === 0) {
        const cluster = openMerger(mergeMs), accumulation = openMerger(mergeMs);
        let previousTime = -Infinity;
        for (const row of dedupedRows) {
            if (row.time < previousTime)
                throw new Error('Canonical resonance inputs are not time ordered');
            previousTime = row.time;
            if (row.time >= since)
                cluster.add(row);
            if (row.time >= accumulationSince)
                accumulation.add(row);
        }
        clusterMerged = cluster.merged;
        accumulationMerged = accumulation.merged;
    }
    else {
        const rows = [...dedupedRows];
        clusterMerged = mergeOpens(rows.filter(row => row.time >= since), mergeMs);
        accumulationMerged = mergeOpens(rows.filter(row => row.time >= accumulationSince), mergeMs);
    }
    const clusterRows = clusterMerged.filter(row => row.action === 'open' && row.notionalUsd >= config.minNotionalUsd);
    const accumulationRows = accumulationMerged.filter(row => row.notionalUsd >= config.minNotionalUsd);
    const signals = [
        ...scanAccumulationSignals(accumulationRows, config, now),
        ...scanClusterSignals(clusterRows, config),
    ].sort(sortSignals);
    const whaleMap = new Map(input.whales.map((item) => [item.id, item]));
    for (const signal of signals) {
        signal.rows = mergeRowsByWhale(signal.rows, whaleMap);
    }
    return {
        hit: signals.length > 0,
        primary: primaryBySignalSide(signals),
        signals,
        emptyText: watched.length
            ? `暂无 ${watched.join(' / ')} 共振或持续加仓信号`
            : '暂无巨鲸共振或持续加仓信号',
    };
}
