'use strict';

const REASON_ZH = {
  S9_DATA_5M_STALE: '5分钟方向数据已过期',
  S9_DATA_1M_STALE: '1分钟K线数据已过期',
  S9_S3_DIRECTION_BLOCK: '市场方向强度不足',
  S9_VOLUME_NOT_EXPANDED: '成交量放大不足',
  S9_CANDLE_QUALITY_BLOCK: '突破K线质量不足',
  S9_VOLATILITY_TOO_LOW: '短周期波动不足',
  S9_VOLATILITY_TOO_HIGH: '短周期波动异常',
  S9_STRUCTURE_STOP_NOT_FOUND: '未找到有效的短周期结构止损',
  S9_STRUCTURE_STOP_TOO_TIGHT: '结构止损距离过近',
  S9_STRUCTURE_STOP_TOO_WIDE: '结构止损距离过远',
  S9_SPREAD_TOO_WIDE: '当前买卖价差过大',
  S9_INSUFFICIENT_BOOK_DEPTH: '当前盘口深度不足',
  S9_COST_DATA_UNAVAILABLE: '无法获取当前交易成本',
  S9_EXPECTED_MOVE_INSUFFICIENT_AFTER_COST: '扣除交易成本后预期空间不足',
  S9_TRADE_INTENT_EXPIRED: '交易机会已过期',
  S9_ENTRY_PRICE_DRIFT_EXCEEDED: '入场价格漂移超过允许范围',
  S9_DIRECTION_NEUTRAL: '5分钟方向为中性，暂不开仓',
  S9_NO_BREAKOUT: '尚未出现有效突破',
  S9_SIGNAL_ALREADY_USED: '同一根已收盘1分钟K线已使用过信号',
  S9_EXPECTED_SLIPPAGE_TOO_HIGH: '预计成交滑点过高',
  S9_ORDERBOOK_STALE: '盘口数据已过期',
  S9_TRADES_STALE: '主动成交数据已过期',
  S9_DATA_DEGRADED: '微观结构数据不完整',
  S9_DIRECTION_FLIP_EXIT: '短周期方向已翻转，执行主动退出',
  S9_TIME_EXIT: '持仓时间达到上限，执行主动退出',
  S9_MARKET_DATA_DEGRADED: '高频策略行情数据不完整',
  S9_FEE_READY: '交易手续费数据已就绪',
  S9_FEE_UNAVAILABLE: '无法获取当前交易手续费',
  S9_PRESUBMIT_REJECTED: '下单前执行检查未通过',
  S9_PRESUBMIT_PASSED: '下单前执行检查已通过',
  S9_IMPLEMENTATION_NOT_READY: 'S9 代码能力尚未全部接通',
  S9_DEMO_PREFLIGHT_NOT_READY: 'S9 尚未具备安全开始模拟盘验证的条件',
  S9_MARKET_DATA_CONNECTED: '高频策略行情已连接',
  S9_MARKET_DATA_DISCONNECTED: '高频策略行情已断开',
  S9_MARKET_DATA_CONNECTING: '正在连接高频行情数据',
  S9_MARKET_DATA_READY: '高频策略行情数据已就绪',
  ACCOUNT_CONTEXT_NOT_READY: '账户上下文未就绪（可信操作用户尚未绑定）',
  OWNER_NOT_READY: '可信操作用户尚未就绪',
  CREDENTIAL_NOT_FOUND: '未找到当前用户的 OKX 交易密钥',
  ACCOUNT_ENV_NOT_READY: '当前账户环境不是 OKX 模拟盘',
  FEE_API_TIMEOUT: '交易手续费查询超时',
  FEE_API_ERROR: '交易手续费查询失败',
  FEE_RESPONSE_INVALID: '交易手续费返回数据无效',
  S9_TRADE_FREQUENCY_HOUR: '滚动一小时开仓次数已达上限',
  S9_TRADE_FREQUENCY_DAY: '当日开仓次数已达上限',
  S9_COOLDOWN: '策略冷却中，暂不开仓',
  SPREAD_WINDOW_WARMING_UP: '价差样本仍在预热，暂不开仓',
  SYMBOL_OWNERSHIP_CONFLICT: '当前交易对仍由其他策略持有，已阻止新的开仓',
  DUST_RESIDUAL_POSITION: '交易所仍存在残余仓位',
  UNRESOLVED_DUST_POSITION: '残余仓位暂时无法自动清理',
  ORPHAN_PROTECTIVE_STOP: '仍存在遗留保护止损',
  ORPHAN_PROTECTIVE_STOP_CLEANUP_FAILED: '遗留保护止损自动清理失败',
  MANUAL_REVIEW_REQUIRED: '需要人工检查交易所状态',
  ENGINE_OWNER_NOT_BOUND: '尚未绑定交易操作用户',
  ALPHA_EXECUTION_USER_NOT_READY: '尚未绑定交易操作用户',
  MARKET_DATA_WARMING_UP: '行情数据预热中',
  MARKET_DATA_STALE: '系统尚未具备交易条件：行情数据未就绪',
  ALPHA_OPENINGS_PAUSED: '新开仓已暂停',
  S6_ENTRIES_BLOCKED: '安全模块已阻止新开仓',
  TAKE_PROFIT: '已达到1.5R止盈',
  CLOSE_VS_EMA20: '收盘价与 EMA20 的位置不符合趋势要求',
  EMA20_VS_EMA50: 'EMA20 与 EMA50 未形成有效趋势排列',
  S3_DIRECTION_BLOCK: '市场方向不支持当前交易方向',
  S3_REGIME_BLOCK: '当前市场状态不适合该策略交易',
  TREND_SLOPE: '趋势斜率不足',
  TREND_QUALITY: '趋势质量不足',
  TREND_QUALITY_BELOW_THRESHOLD: '趋势质量不足',
  ADX: 'ADX 趋势强度不足',
  ADX14: 'ADX 趋势强度不足',
  COND_ADX14: 'ADX 趋势强度不足',
  EXPECTED_EDGE: '预期交易空间不足',
  EXPECTED_EDGE_TOO_LOW: '预期交易空间不足',
  EDGE_UNAVAILABLE: '预期优势估计不可用',
  VOLATILITY_CONDITION: '波动率条件不满足',
  S1_STRUCTURE_STOP_NOT_FOUND: '未找到有效的结构止损位置',
  INVALID_STOP_PRICE: '止损价格无效',
  S5_BUDGET_BLOCK: '风险预算不足，已阻止开仓',
  DUPLICATE_CLOSED_CANDLE: '同一根已收盘K线已使用过信号',
  S1_DISABLED: 'S1 当前未启用',
  S1_NO_DIRECTION: '当前没有有效交易方向',
  S1_LONG_OK: '多头条件满足',
  S1_SHORT_OK: '空头条件满足',
  MISSING_PRICE_OR_ATR: '缺少价格或 ATR 数据',
  POSITION_QTY_MISMATCH: '仓位数量与交易所不一致',
  POSITION_SIDE_MISMATCH: '仓位方向与交易所不一致',
  RECONCILIATION_NOT_MATCHED: '当前交易状态对账未一致',
  CONFIG_INVALID: '策略配置无效',
  S6_BLOCKED: '安全检查已阻止新的交易',
  S6_ENTRIES_BLOCKED: '安全模块已阻止新开仓',
  MARKET_DATA_WARMING_UP: '行情数据预热中',
  MARKET_DATA_STALE: '系统尚未具备交易条件：行情数据未就绪',
};

const STATUS_ZH = {
  READY: '就绪',
  NOT_READY: '未就绪',
  UNVERIFIED: '未验证',
  VERIFIED: '已验证',
  BLOCKED: '已阻止',
  RESEARCH: '研究中',
  PRODUCTION: '生产',
  DEMO_VALIDATION: '模拟盘验证',
  WARMING_UP: '预热中',
  STALE: '数据已过期',
  OFFLINE: '离线',
  ONLINE: '在线',
  PAUSED: '已暂停',
  RUNNING: '运行中',
  DEGRADED: '降级',
  OFF: '关闭',
  HEALTHY: '健康',
  FLAT: '空仓',
  MATCHED: '已对齐',
  EXECUTE: '可执行',
  SHADOW: '影子模式',
  OKX_DEMO: 'OKX 模拟盘',
  OKX_LIVE: 'OKX 实盘',
  LONG: 'LONG',
  SHORT: 'SHORT',
  BULLISH: '看多',
  BEARISH: '看空',
  NEUTRAL: '中性',
  ALLOW: '允许',
  NO_TRADE: '本轮不交易',
  CANDIDATE: '候选',
  ACTIVE: '活跃',
  PARTIALLY_FILLED: '部分成交',
  PARTIAL: '部分成交',
  FILLED: '已成交',
  SUBMITTED: '已提交',
  REJECTED: '已拒绝',
  CANCELLED: '已取消',
  CANCELED: '已取消',
  EXPIRED: '已过期',
  CREATED: '已创建',
  CONNECTED: '已连接',
  DISCONNECTED: '已断开',
  RECONNECTING: '重连中',
};

const EVENT_ZH = {
  STRATEGY_NO_TRADE: '本轮不交易',
  STRATEGY_CANDIDATE: '出现可交易信号候选',
  TRADE_INTENT_CREATED: '交易意图已创建',
  ORDER_INTENT_CREATED: '订单意图已创建',
  S9_NO_TRADE: '本轮不交易',
  S9_TRADE_INTENT_CREATED: '交易意图已创建',
  S9_ORDER_INTENT_CREATED: '订单意图已创建',
  ORDER_SUBMITTED: '开仓订单已提交，等待成交',
  ORDER_PARTIALLY_FILLED: '开仓部分成交',
  ORDER_FILLED: '仓位建立完成',
  ORDER_REJECTED: '开仓订单已拒绝',
  PROTECTIVE_STOP_ACTIVE: '保护止损已生效',
  PROTECTIVE_STOP_AMENDED: '保护止损覆盖数量已调整',
  PROTECTIVE_STOP_TRIGGERED: '保护止损已触发',
  TAKE_PROFIT_TRIGGERED: '达到 1.5R 止盈条件，正在执行平仓',
  TIME_EXIT_TRIGGERED: '持仓已达到最长持有时间，正在执行平仓',
  DIRECTION_FLIP_EXIT_TRIGGERED: '5分钟方向发生反转，正在执行平仓',
  POSITION_OPENED: '仓位已建立',
  POSITION_CLOSED: '仓位已全部平仓',
  POSITION_REDUCED: '仓位已减少',
  OWNERSHIP_RELEASED: '仓位及关联订单已清理完成，交易对已释放',
  ENGINE_START: '交易引擎已启动',
  ENGINE_STARTED: '交易引擎已启动',
  ENGINE_PAUSE: '交易引擎已暂停',
  ENGINE_PAUSED: '交易引擎已暂停',
  S9_ORDERBOOK_STALE: '盘口数据已过期',
  S9_FEE_READY: '交易手续费数据已就绪',
  S9_FEE_UNAVAILABLE: '无法获取当前交易手续费',
  S9_MARKET_DATA_CONNECTED: '行情数据连接正常',
  S9_MARKET_DATA_DISCONNECTED: '行情数据连接已断开',
  S9_MARKET_DATA_CONNECTING: '正在连接高频行情数据',
  S9_MARKET_DATA_DEGRADED: '高频策略行情数据不完整',
  S9_MARKET_DATA_READY: '高频策略行情数据已就绪',
  MARKET_DATA_CONNECTED: '行情数据连接正常',
  MARKET_DATA_DISCONNECTED: '行情数据连接已断开',
  STARTUP_RECOVERY_STARTED: '启动恢复检查进行中',
  STARTUP_RECOVERY_READY: '启动恢复检查已完成',
  STARTUP_RECOVERY_FAILED: '启动恢复检查失败',
  RECONCILIATION_MATCHED: '交易状态对账一致',
  RECONCILIATION_MISMATCH: '仓位与交易所对账不一致',
  RECONCILIATION_NOT_MATCHED: '当前交易状态对账未一致',
  S6_BLOCK: '安全检查已阻止新的交易',
  S6_LOCK: '安全检查已锁定交易引擎',
  CONFIG_INVALID: '策略配置无效',
  CONFIG_LOADED: '策略配置已加载',
  SYMBOL_OWNERSHIP_CONFLICT: '当前交易对仍由其他策略持有，已阻止新的开仓',
  ORDER_EXPIRED: '订单已过期',
  TRADE_INTENT_EXPIRED: '交易意图已过期',
  OWNERSHIP_CREATED: '仓位所有权已建立',
  OWNERSHIP_UPDATED: '仓位所有权已更新',
  OWNERSHIP_RELEASED: '仓位及关联订单已清理完成，交易对已释放',
  POSITION_UPDATED: '仓位已更新',
  EXIT_SUBMITTED: '平仓订单已提交',
  EXIT_PARTIALLY_FILLED: '平仓部分成交',
  EXIT_FILLED: '平仓已成交',
};

const STRATEGY_NAME_ZH = {
  S1: '趋势跟踪',
  S2: '极端情绪反转',
  S3: '市场状态',
  S4: '执行时机',
  S5: '风险预算',
  S6: '安全模块',
  S7: '策略健康',
  S8: '巨鲸行为共振',
  S9: '高频动量突破',
};

function reasonZh(code) {
  const key = String(code || '').trim();
  if (!key) return '';
  return REASON_ZH[key] || `未识别的交易提示（${key}）`;
}

function statusZh(value) {
  const key = String(value || '').trim();
  if (!key) return '';
  return STATUS_ZH[key.toUpperCase()] || STATUS_ZH[key] || `未识别的系统状态（${key}）`;
}

function eventZh(eventType) {
  const key = String(eventType || '').trim();
  if (!key) return '';
  return EVENT_ZH[key] || `未识别的系统状态（${key}）`;
}

function strategyNameZh(strategyId) {
  const key = String(strategyId || '').trim().toUpperCase();
  if (!key) return '';
  const name = STRATEGY_NAME_ZH[key];
  return name ? `${key} ${name}` : key;
}

module.exports = {
  REASON_ZH,
  STATUS_ZH,
  EVENT_ZH,
  STRATEGY_NAME_ZH,
  reasonZh,
  statusZh,
  eventZh,
  strategyNameZh,
};
