import { createApp, h } from 'vue';
import { createPinia } from 'pinia';
import { ElAlert, ElAutocomplete, ElButton, ElCard, ElDialog, ElEmpty, ElForm, ElFormItem, ElIcon, ElInput, ElOption, ElPagination, ElPopover, ElSelect, ElSkeleton, ElTag, ElTooltip, ElConfigProvider, ElLoading } from 'element-plus';
import zhCn from 'element-plus/es/locale/lang/zh-cn';
import 'element-plus/es/components/alert/style/css';
import 'element-plus/es/components/autocomplete/style/css';
import 'element-plus/es/components/button/style/css';
import 'element-plus/es/components/card/style/css';
import 'element-plus/es/components/dialog/style/css';
import 'element-plus/es/components/empty/style/css';
import 'element-plus/es/components/form/style/css';
import 'element-plus/es/components/form-item/style/css';
import 'element-plus/es/components/icon/style/css';
import 'element-plus/es/components/input/style/css';
import 'element-plus/es/components/option/style/css';
import 'element-plus/es/components/pagination/style/css';
import 'element-plus/es/components/popover/style/css';
import 'element-plus/es/components/select/style/css';
import 'element-plus/es/components/skeleton/style/css';
import 'element-plus/es/components/tag/style/css';
import 'element-plus/es/components/tooltip/style/css';
import 'element-plus/es/components/message/style/css';
import 'element-plus/es/components/message-box/style/css';
import 'element-plus/es/components/loading/style/css';
import 'element-plus/theme-chalk/dark/css-vars.css';
import App from './App.vue';
import router from './router';
import './style.css';

const app = createApp({ render: () => h(ElConfigProvider, { locale: zhCn }, { default: () => h(App) }) });
app.use(createPinia());
app.use(router);
for (const component of [ElAlert, ElAutocomplete, ElButton, ElCard, ElDialog, ElEmpty, ElForm, ElFormItem, ElIcon, ElInput, ElOption, ElPagination, ElPopover, ElSelect, ElSkeleton, ElTag, ElTooltip]) app.component(component.name!, component);
app.use(ElLoading);
app.mount('#app');
