<script setup lang="ts">
import { locatedCoinFilter } from '@/utils/alertGrouping';
import WhaleValidation from "@/components/WhaleValidation.vue";
import { whaleAssetLabel } from '@/utils/whaleAssetLabel';
import MobileScroll from './MobileScroll.vue';
import {computed,ref,nextTick,watch} from 'vue';import type {WhaleProfile} from '@/types';import {visibleWhalePositions} from '@/utils/whaleCardUtils';import {whaleCardTitle} from '@/utils/whaleReference';import {formatUsd,formatPrice,formatPnl} from '@/utils/format';import {useWhalePreferredAssets} from '@/utils/whalePreferredAssets';import MobileSheet from './MobileSheet.vue';
const props=defineProps<{whales:WhaleProfile[];loading:boolean;refresh:()=>Promise<unknown>}>();const emit=defineEmits<{detail:[whale:WhaleProfile]}>();const coin=ref('all'),query=ref(''),filters=ref(false),focused=ref('');const scroll=ref<HTMLElement|null>(null);
const market=ref('all');
const coins=useWhalePreferredAssets();
watch(coins, values=>{if(coin.value!=='all'&&!values.includes(coin.value))coin.value='all';});
const rows=computed(()=>props.whales.map(w=>({whale:w,positions:visibleWhalePositions(w,coin.value).filter(p=>market.value==='all'||(p.coin.includes(':')?market.value==='extended':market.value==='native'))})).filter(r=>r.positions.length&&`${r.whale.name} ${r.whale.address}`.toLowerCase().includes(query.value.toLowerCase())));
async function focusWhale(value:{id:string;coin?:string}){market.value='all';coin.value=locatedCoinFilter(coin.value,value.coin,coins.value);query.value='';focused.value=value.id;await nextTick();const card=Array.from(scroll.value?.querySelectorAll<HTMLElement>('[data-whale]')||[]).find(el=>el.dataset.whale===value.id);card?.scrollIntoView({behavior:'smooth',block:'center'});}
defineExpose({focusWhale,initialize:()=>Promise.resolve()});
</script><template><section class="h5-whales"><header class="h5-tools"><span>{{rows.length}} 个巨鲸账户</span><WhaleValidation :coin="coin" /><button @click="filters=true">筛选 ⌄</button></header><MobileScroll :refresh="refresh" :busy="loading"><div ref="scroll"><p v-if="!rows.length" class="h5-empty">{{loading?'正在加载巨鲸…':'暂无符合条件的持仓账户'}}</p><article v-for="row in rows" :key="row.whale.id" :data-whale="row.whale.id" class="h5-card h5-whale" :class="{selected:focused===row.whale.id}"><button class="h5-whale-title" @click="emit('detail',row.whale)"><b>{{whaleCardTitle(row.whale)}}</b><span>详情 ›</span></button><p class="h5-address">{{row.whale.address}}</p><div v-for="(pos,i) in row.positions.slice(0,3)" :key="pos.coin+pos.side+i" class="h5-position"><div class="h5-between"><b>{{whaleAssetLabel(pos.coin)}}</b><span :class="pos.side==='long'?'positive':'negative'">{{pos.side==='long'?'做多':'做空'}}</span></div><div class="h5-between"><span>仓位 {{formatUsd(pos.positionValue)}}</span><b :class="pos.unrealizedPnl>=0?'positive':'negative'">{{formatPnl(pos.unrealizedPnl)}}</b></div><small>均价 {{formatPrice(pos.entryPx)}} · {{pos.leverage==null?'杠杆未知':pos.leverage+'×'}}</small></div><button v-if="row.positions.length>3" class="h5-more" @click="emit('detail',row.whale)">查看全部 {{row.positions.length}} 个仓位</button></article></div></MobileScroll><MobileSheet v-model="filters" title="巨鲸筛选"><label class="h5-field">市场<select v-model="market" @change="coin='all'"><option value="all">全部市场</option><option value="native">默认合约</option><option value="extended">TradFi / 扩展市场</option></select></label><label class="h5-field">币种<select v-model="coin"><option value="all">全部币种</option><option v-for="c in coins" :key="c" :value="c">{{whaleAssetLabel(c)}}{{c.includes(':') ? ' · '+c.split(':')[0] : ''}}</option></select></label><label class="h5-field">账户<input v-model="query" placeholder="名称或地址"></label><button class="h5-primary" @click="filters=false">完成</button></MobileSheet></section></template>
