<script setup lang="ts">
import MobileScroll from './MobileScroll.vue';
import {radarClient} from '@/utils/radarRealtime';
import {ref,nextTick,computed,watch} from 'vue';
import type {ShortRadarModel} from '../TradFiBoard.vue';
import ContractLogo from '../ContractLogo.vue';import ContractDetailLink from '../ContractDetailLink.vue';import CandlestickChart from '../CandlestickChart.vue';import MobileSheet from './MobileSheet.vue';
const props=defineProps<{model:ShortRadarModel}>();const filters=ref(false),large=ref(false);const chart=ref<HTMLElement|null>(null);
async function select(symbol:string){props.model.selectSymbol(symbol);await nextTick();chart.value?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
const limit=ref(20);const list=computed(()=>(props.model.filteredMarketRows).slice(0,limit.value));const hasMore=computed(()=>limit.value<(props.model.filteredMarketRows).length);
watch(()=>[props.model.searchText,props.model.assetFilter,props.model.directionFilter,props.model.activeInterval,props.model.marketSort,props.model.marketOrder],()=>{limit.value=20;});
async function refresh(){await radarClient.ensure();if(radarClient.error.value)throw new Error(radarClient.error.value);}
</script>
<template><MobileScroll :refresh="refresh" refresh-text="已检查数据连接，行情持续实时更新" :more="()=>{limit+=20}" :has-more="hasMore"><div class="h5-radar-body">
<div class="h5-tools"><div class="h5-chips"><button v-for="item in model.intervals" :key="item.id" :class="{active:model.activeInterval===item.id}" :aria-pressed="model.activeInterval===item.id" @click="model.activeInterval=item.id">{{item.label}}</button></div><button @click="filters=true">筛选 ⌄</button></div>
<div class="h5-between h5-section-title"><span>我的关注</span><button @click="model.openAddContractDialog()">＋ 添加</button></div>
<div class="h5-watch-grid"><article v-for="row in model.pagedWatchRows" :key="row.symbol" class="h5-watch" :class="{selected:model.selected===row.symbol}"><button class="h5-watch-main" @click="select(row.symbol)"><div class="h5-instrument"><ContractLogo :symbol="row.symbol" :asset-type="model.assetType(row.symbol)"/><span>{{row.symbol.replace(/USDT$/,'')}}<small>{{model.assetLabel(row.symbol)}}</small></span></div><b>{{model.formatPrice(row.quote?.lastPrice)}}</b><strong :class="model.changeClass(row.change)">{{model.formatChange(row.change)}}</strong><small>{{model.isQuoteStale(row.quote)?'缓存行情':'实时行情'}}</small></button><div class="h5-watch-actions"><button @click="model.openAiAnalysis(row.symbol)">AI</button><ContractDetailLink :symbol="row.symbol" :asset-type="model.assetType(row.symbol)" icon-only/><button :aria-label="`取消关注 ${row.symbol}`" @click="model.toggleWatch(row.symbol)">★</button></div></article><p v-if="!model.pagedWatchRows.length" class="h5-empty">暂无关注标的，可从列表添加</p></div>
<div v-if="model.watchPageCount>1" class="h5-watch-pages"><button v-for="n in model.watchPageCount" :key="n" :class="{active:model.watchPage===n}" :aria-label="`关注第 ${n} 组`" @click="model.watchPage=n">{{n}}</button></div>
<section ref="chart" class="h5-card h5-chart"><div class="h5-between"><strong>{{model.assetLabel(model.selected)}}</strong><button @click="large=true">放大 ↗</button></div><div class="h5-chart-price">{{model.formatPrice(model.selectedQuote?.lastPrice)}} <span :class="model.changeClass(model.changeValue(model.selectedQuote||undefined,model.activeInterval))">{{model.formatChange(model.changeValue(model.selectedQuote||undefined,model.activeInterval))}}</span></div><div class="h5-range"><span>区间高 {{model.formatPrice(model.selectedRange.high)}}</span><span>区间低 {{model.formatPrice(model.selectedRange.low)}}</span></div><div class="h5-chips"><button :class="{active:model.chartInterval==='5m'}" :aria-pressed="model.chartInterval==='5m'" @click="model.chartInterval='5m'">5 分钟</button><button :class="{active:model.chartInterval==='1h'}" :aria-pressed="model.chartInterval==='1h'" @click="model.chartInterval='1h'">1 小时</button></div><div class="h5-candles"><CandlestickChart v-if="model.chartBars.length && !large" :bars="model.chartBars" :symbol="model.selected" :interval="model.chartInterval"/><p v-else-if="!model.chartBars.length" class="h5-empty">{{model.chartLoading?'正在读取走势…':model.chartError||'暂无走势图'}}</p></div><p v-if="model.chartError" class="h5-notice">{{model.chartError}}</p></section>
<header class="h5-section-title h5-between"><span>其他合约</span><button @click="model.sortMarket('change')">涨跌幅 {{model.marketOrder==='desc'?'↓':'↑'}}</button></header><article v-for="row in list" :key="row.symbol" class="h5-contract"><button class="h5-contract-main" @click="select(row.symbol)"><ContractLogo :symbol="row.symbol" :asset-type="model.assetType(row.symbol)"/><span>{{row.symbol.replace(/USDT$/,'')}}<small>{{model.assetLabel(row.symbol)}}</small></span><span :class="model.changeClass(row.change)">{{model.formatChange(row.change)}}<small>{{model.formatPrice(row.quote?.lastPrice)}}</small></span></button><ContractDetailLink :symbol="row.symbol" :asset-type="model.assetType(row.symbol)" icon-only/><button class="h5-contract-watch" :aria-label="`关注 ${row.symbol}`" @click="model.toggleWatch(row.symbol)">{{model.isWatched(row.symbol)?'★':'☆'}}</button></article><p v-if="!list.length" class="h5-empty">{{model.marketLoading?'正在加载合约…':'没有符合筛选条件的合约'}}</p><p class="h5-muted">{{model.marketError || '行情更新于 '+model.quoteTimestamp}}</p>
<MobileSheet v-model="filters" title="短期趋势筛选"><label class="h5-field">搜索<input v-model="model.searchText" placeholder="代码或名称"></label><label class="h5-field">类别<select v-model="model.assetFilter"><option v-for="c in model.categories" :value="c.id" :key="c.id">{{c.label}}</option></select></label><label class="h5-field">方向<select v-model="model.directionFilter"><option value="ALL">全部</option><option value="UP">上涨</option><option value="DOWN">下跌</option></select></label><label class="h5-field">排序<select v-model="model.marketSort"><option value="absoluteChange">涨跌幅绝对值</option><option value="change">涨跌幅</option><option value="price">现价</option></select></label><label class="h5-field">顺序<select v-model="model.marketOrder"><option value="desc">从高到低</option><option value="asc">从低到高</option></select></label><button @click="model.marketSort='absoluteChange';model.marketOrder='desc'">重置排序</button><button class="h5-primary" @click="filters=false">完成</button></MobileSheet>
<MobileSheet v-model="large" :title="model.selected+' · K 线'"><div class="h5-large-chart"><CandlestickChart v-if="large && model.chartBars.length" :bars="model.chartBars" :symbol="model.selected" :interval="model.chartInterval"/><p v-else>暂无走势图</p></div></MobileSheet>
</div></MobileScroll></template>
