<script setup lang="ts">
import MobileScroll from './MobileScroll.vue';
import {radarClient} from '@/utils/radarRealtime';
import {ref,nextTick,computed,watch} from 'vue';import type {LongRadarModel} from '../RadarLongTrend.vue';import type {TrendRow} from '@/utils/radarRealtime';
import ContractLogo from '../ContractLogo.vue';import ContractDetailLink from '../ContractDetailLink.vue';import CandlestickChart from '../CandlestickChart.vue';import MobileSheet from './MobileSheet.vue';
const props=defineProps<{model:LongRadarModel}>();const filters=ref(false),large=ref(false);const chart=ref<HTMLElement|null>(null);
async function select(row:TrendRow){props.model.selectRow(row);await nextTick();chart.value?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
const limit=ref(20);const list=computed(()=>(props.model.data?.allRows||[]).slice(0,limit.value));const hasMore=computed(()=>limit.value<(props.model.data?.allRows||[]).length);
watch(()=>[props.model.search,props.model.assetGroup,props.model.direction,props.model.days,props.model.sort,props.model.order],()=>{limit.value=20;});
async function refresh(){await radarClient.ensure();if(radarClient.error.value)throw new Error(radarClient.error.value);}
</script>
<template><MobileScroll :refresh="refresh" refresh-text="已检查数据连接，行情持续实时更新" :more="()=>{limit+=20}" :has-more="hasMore"><div class="h5-radar-body"><div class="h5-tools"><div class="h5-chips"><button v-for="g in model.assetGroups" :key="g.id" :class="{active:model.assetGroup===g.id}" :aria-pressed="model.assetGroup===g.id" @click="model.toggleAssetGroup(g.id)">{{g.label}}</button></div><button @click="filters=true">筛选 ⌄</button></div><div class="h5-section-title h5-between"><span>我的关注</span><small>近 {{model.displayedDays}} 天</small></div><div class="h5-watch-grid"><article v-for="row in model.cards" :key="row.symbol" class="h5-watch" :class="{selected:model.selected?.symbol===row.symbol}"><button class="h5-watch-main" @click="select(row)"><div class="h5-instrument"><ContractLogo :symbol="row.symbol"/><span>{{row.symbol.replace(/USDT$/,'')}}<small>{{row.name}}</small></span></div><b>{{model.price(row.currentPrice)}}</b><strong :class="model.color(row.change)">{{model.pct(row.change)}}</strong><small>{{row.priceStale?'缓存现价 · ':''}}{{model.label(row)}}</small></button><div class="h5-watch-actions"><small>{{row.days}} 天</small><ContractDetailLink :symbol="row.symbol" :asset-type="row.assetType" :name="row.name" icon-only/><button :aria-label="`取消关注 ${row.symbol}`" @click="model.toggleWatch(row.symbol)">★</button></div></article><p v-if="!model.cards.length" class="h5-empty">点击列表星标添加关注</p></div><div v-if="model.cardPages>1" class="h5-watch-pages"><button v-for="n in model.cardPages" :key="n" :class="{active:model.cardPage===n}" :aria-label="`关注第 ${n} 组`" @click="model.cardPage=n">{{n}}</button></div>
<section ref="chart" class="h5-card h5-chart"><div class="h5-between"><strong>{{model.selected?.name||'选择一个合约'}}</strong><button @click="large=true">放大 ↗</button></div><div class="h5-chart-price">{{model.price(model.selected?.currentPrice)}} <span :class="model.color(model.selected?.change)">{{model.pct(model.selected?.change)}}</span></div><div class="h5-range"><span>区间高 {{model.price(model.selectedRange?.high)}}</span><span>区间低 {{model.price(model.selectedRange?.low)}}</span></div><div class="h5-chips"><button v-for="d in [30,60,90]" :key="d" :class="{active:model.days===d}" :aria-pressed="model.days===d" @click="model.days=d">{{d}} 天</button></div><div class="h5-candles"><CandlestickChart v-if="model.dailyBars.length && !large" :bars="model.dailyBars" :visible-count="model.displayedDays+1" :symbol="model.selected?.symbol||''" interval="1d"/><p v-else-if="!model.dailyBars.length" class="h5-empty">{{model.dailyChart?.error||'日线数据待更新'}}</p></div><details class="h5-details"><summary>更多趋势指标与数据口径</summary><p v-for="d in [30,60,90] as const" :key="d">近 {{d}} 天：{{model.pct(model.selected?.periodChanges?.[d])}}</p><p>最大回撤：{{model.pct(model.selected?.maxDrawdown)}} · 趋势分：{{model.selected?.score??'—'}}</p><p>{{model.selected?.reason || model.selected?.adjustmentNote}} {{model.selected?.stale?'当前为缓存日线':''}}</p><p>统计已收盘的 UTC 日线；历史不足时按实际天数计算，不补齐或年化。</p></details></section>
<header class="h5-between h5-section-title"><span>传统金融合约</span><button @click="model.sortBy('change')">区间涨跌 {{model.order==='desc'?'↓':'↑'}}</button></header><article v-for="row in list" :key="row.symbol" class="h5-contract"><button class="h5-contract-main" @click="select(row)"><ContractLogo :symbol="row.symbol"/><span>{{row.symbol.replace(/USDT$/,'')}}<small>{{row.name}}</small></span><span :class="model.color(row.change)">{{model.pct(row.change)}}<small>{{model.price(row.currentPrice)}}</small></span></button><ContractDetailLink :symbol="row.symbol" :asset-type="row.assetType" :name="row.name" icon-only/><button class="h5-contract-watch" :aria-label="`关注 ${row.symbol}`" @click="model.toggleWatch(row.symbol)">{{model.watchedSymbols.includes(row.symbol)?'★':'☆'}}</button></article><p v-if="!list.length" class="h5-empty">{{model.emptyMessage}}</p><p class="h5-notice">{{model.error||model.data?.error}}</p>
<MobileSheet v-model="filters" title="长期趋势筛选"><label class="h5-field">搜索<input v-model="model.search" placeholder="代码或名称"></label><label class="h5-field">趋势<select v-model="model.direction"><option value="ALL">全部</option><option value="UP">持续走强</option><option value="DOWN">持续走弱</option><option value="TURN_UP">近期转强</option><option value="TURN_DOWN">近期转弱</option><option value="NEUTRAL">震荡</option></select></label><label class="h5-field">排序<select v-model="model.sort"><option value="score">趋势分</option><option value="change">区间涨跌</option><option value="monthChange">近30天涨跌</option></select></label><label class="h5-field">顺序<select v-model="model.order"><option value="desc">从高到低</option><option value="asc">从低到高</option></select></label><button @click="model.sort='score';model.order='desc'">重置排序</button><button class="h5-primary" @click="filters=false">完成</button></MobileSheet><MobileSheet v-model="large" :title="(model.selected?.symbol||'合约')+' · 日线'"><div class="h5-large-chart"><CandlestickChart v-if="large && model.dailyBars.length" :bars="model.dailyBars" :visible-count="model.displayedDays+1" :symbol="model.selected?.symbol||''" interval="1d"/><p v-else>暂无走势图</p></div></MobileSheet>
</div></MobileScroll></template>
